---

# Extractor configuration
extractors:
    strings:
        minimum_string_length: 10
        minimum_occurances: 1
    dynamic:
        qiling_rootfs: tests/rootfs
        log_folder: tests/logs
    opcodes:
        groups:
            - arithmetical_operations: [
                "add",
                "inc",
                "sub",
                "mul",
                "imul",
                "div",
                "idiv"
            ]
            - logical_operations: [
                "and",
                "or",
                "xor",
            ]
            - bit_operations: [
                "ror",
                "rol",
                "test",
                "bt",
                "bsr",
                "bsf"
            ]
            - data_transfer: [
                "mov*",
                "lods*",
                "xchg"
            ]
            - data_dimenstion_conversion: [
                "cdq*",
                "cbw",
                "cwd"
            ]
            - pointers_work: [
                "lea",
                "lds",
                "les"
            ]
            - comparision: [
                "cmp",
                "scas"
            ]
            - jump: [
                "j*"
            ]
            - stack: [
                "call",
                "ret",
                "push",
                "pop"
            ]
            - io: [
                "out*",
                "in"
            ]
            - boolean_creation: [
                "set*"
            ]
            - others: [
                "rep",
                "nop",
                "wait"
            ]
        min_ignored_percent: 0.05

# Database configuration
database:
    host: localhost
    port: 27017
    username: admin
    password: admin
    database: CODENAME