---

# Extractor configuration
extractors:
    strings:
        minimum_string_length: 10
        minimum_occurances: 1

# Database configuration
database:
    host: localhost
    port: 27017
    username: admin
    password: admin
    database: CODENAME