---

master_server:
    cli:
        banner: |
            \n
                  ██  ██  ██
               ▄▄ ██  ▄▄  ██  ▄▄   ▄▄▄
            ▄█▄ ████  ██  ██ ▄▀  ▄█████
            ██▀ ▀▀██  ██  ██▀█▄  ██
            ▀███████  ██  ██  ██ ▀█▄▄▄▀
            \n
            Platform for automatic analysis of malicious applications
            using artificial intelligence algorithms
        prompt: "dike :wavy_dash: "
        citation_line_prefix: "▒    "
        max_string_len: 30
        string_part_hidden: ...
    answers_checking_interval: 1

subordintate_server:
    hostname: 0.0.0.0
    port: 1234

predictor_collector_server:
    hostname: 0.0.0.0
    port: 10101
    is_debug: True

extractors:
    strings:
        minimum_string_length: 10
        minimum_occurances: 1
    opcodes:
        categories: !include opcodes_categories.yaml
        allow_multiple_categories: 1
        verbose: True
        min_ignored_percent: 0.03
    apis:
        categories: !include api_categories.yaml
        allow_multiple_categories: 1
        verbose: True
        min_ignored_percent: 0.03
        ignored_prefixes:
            - Rtl
            - Csr
            - Dbg
            - Ldr
            - Nt
        ignored_suffixes:
            - Ex
            - ExEx
            - A
            - W

dataset_builder:
    malware_families: !include malware_families.yaml
    malware_benign_vote_ratio: 2
    min_ignored_percent: 0.03

preprocessors:
    ngrams:
        n: 2
        to_lowercase: True
        valid_charset: LOWERCASE

machine_learning:
    default_min_thresholds:
        malice:
            suspect: 0.3
            malicious: 0.6
        class_membership: 0.2
    retraining:
        stringified_time: "00:00"
        workers_count: 4
    prediction:
        model_lifetime: 60
        ticket_lifetime: 60
        ticket_length: 32
        checking_interval: 10

database:
    hostname: localhost
    port: 27017
    database: dike

secrets: !include secrets.yaml