---

master_server:
    cli:
        banner: |
            ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
            █░▄▀██▄██░█▀█░▄▄█
            █░█░██░▄█░▄▀█░▄▄█
            █▄▄██▄▄▄█▄█▄█▄▄▄█
            ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
        prompt: dike
    answers_checking_interval: 1

subordintate_server:
    hostname: 0.0.0.0
    port: 1234
    service_name: dike

extractors:
    strings:
        minimum_string_length: 10
        minimum_occurances: 1
    opcodes:
        categories: !include opcodes_categories.yaml
        min_ignored_percent: 0.05
    apis:
        categories: !include api_categories.yaml
        min_ignored_percent: 0.05
        ignored_prefixes:
            - Rtl
            - Csr
            - Dbg
            - Ldr
            - Nt
        ignored_suffixes:
            - Ex
            - ExEx
            - A
            - W

dataset_builder:
    malware_categories: !include malware_categories.yaml

database:
    hostname: localhost
    port: 27017
    database: dike

secrets: !include secrets.yaml