# Services (modify the bind mount if the user is another one)
services:
    leader:
        build: leader
        volumes:
            - /home/iosif/dike:/dike
        networks:
            network:
                ipv4_address: 192.168.0.2
    first_subordinate:
        build: subordinate
        volumes:
            - /home/iosif/dike:/dike
        networks:
            network:
                ipv4_address: 192.168.0.10
    second_subordinate:
        build: subordinate
        volumes:
            - /home/iosif/dike:/dike
        networks:
            network:
                ipv4_address: 192.168.0.11
    predictor-collector:
        build: predictor-collector
        volumes:
            - /home/iosif/dike:/dike
        networks:
            network:
                ipv4_address: 192.168.0.100

# Network
networks:
    network:
        ipam:
            driver: default
            config:
                - subnet: "192.168.0.0/24"