services:
    leader:
        build: leader
        container_name: leader
        volumes:
            - /opt/dike:/opt/dike
        networks:
            network:
                ipv4_address: 192.168.0.2

    first_subordinate:
        build: subordinate
        container_name: first_subordinate
        volumes:
            - /opt/dike:/opt/dike
            - /opt/ghidra:/opt/ghidra
        networks:
            network:
                ipv4_address: 192.168.0.10

    second_subordinate:
        build: subordinate
        container_name: second_subordinate
        volumes:
            - /opt/dike:/opt/dike
            - /opt/ghidra:/opt/ghidra
        networks:
            network:
                ipv4_address: 192.168.0.11

    predictor-collector:
        build: predictor-collector
        container_name: predictor-collector
        volumes:
            - /opt/dike:/opt/dike
            - /opt/ghidra:/opt/ghidra
        networks:
            network:
                ipv4_address: 192.168.0.100

networks:
    network:
        ipam:
            driver: default
            config:
                - subnet: "192.168.0.0/24"